name: Mandate updateBranch

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run branch update check
        env:
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: python3 .github/scripts/check_branch_update.py
